spring.application.name=service-registry
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Logging
logging.level.root=INFO
logging.level.com.founderlink.registry=DEBUG
logging.file.name=logs/service-registry.log