-- =============================================================================
-- user-service/seed.sql
-- Table: users
-- User IDs: 1001–1200 (MUST match auth-service exactly)
-- Role: stored as STRING enum (FOUNDER / INVESTOR / COFOUNDER / ADMIN)
-- No cross-DB queries — all IDs are pre-defined constants
-- Idempotent: INSERT IGNORE 
-- =============================================================================

SET NAMES utf8mb4;
SET foreign_key_checks = 0;

INSERT IGNORE INTO users (id, name, email, skills, experience, bio, portfolio_links, role, updated_at) VALUES
-- FOUNDER users (1001–1060)
(1001,'seed_Aarav Shah','seed_user1@test.com','Java,Spring Boot,React','5 years in SaaS',
 'Passionate founder building the next-gen startup ecosystem.',
 'https://github.com/seed_aarav','FOUNDER','2024-09-01 10:00:00'),
(1002,'seed_Vivaan Mehta','seed_user2@test.com','Python,FastAPI,Vue.js','3 years in EdTech',
 'EdTech entrepreneur disrupting online learning.',
 'https://linkedin.com/in/seed_vivaan','FOUNDER','2024-09-01 10:00:00'),
(1003,'seed_Aditya Kumar','seed_user3@test.com','Node.js,MongoDB,Angular','4 years in FinTech',
 'Building frictionless payment experiences for India.',
 'https://github.com/seed_aditya','FOUNDER','2024-09-01 10:00:00'),
(1004,'seed_Vihaan Singh','seed_user4@test.com','Golang,Kubernetes,AWS','6 years in DevOps',
 'Cloud-native infrastructure enthusiast turned founder.',
 'https://portfolio.seed_vihaan.dev','FOUNDER','2024-09-01 10:00:00'),
(1005,'seed_Arjun Gupta','seed_user5@test.com','Rust,WebAssembly,TypeScript','4 years in Gaming',
 'Gaming tech founder focused on low-latency multiplayer.',
 'https://github.com/seed_arjun','FOUNDER','2024-09-01 10:00:00'),
(1006,'seed_Sai Sharma','seed_user6@test.com','ML,TensorFlow,Python','7 years in AI/ML',
 'AI-first entrepreneur building predictive analytics.',
 'https://kaggle.com/seed_sai','FOUNDER','2024-09-01 10:00:00'),
(1007,'seed_Reyansh Verma','seed_user7@test.com','Swift,iOS,Objective-C','3 years in Mobile',
 'iOS developer turned healthcare app founder.',
 'https://apps.apple.com/seed_reyansh','FOUNDER','2024-09-01 10:00:00'),
(1008,'seed_Ayaan Nair','seed_user8@test.com','Flutter,Dart,Firebase','2 years in AgriTech',
 'Connecting farmers with markets via mobile.',
 'https://github.com/seed_ayaan','FOUNDER','2024-09-01 10:00:00'),
(1009,'seed_Krishna Pillai','seed_user9@test.com','React Native,GraphQL,PostgreSQL','5 years in LegalTech',
 'Democratizing legal services through technology.',
 'https://linkedin.com/in/seed_krishna','FOUNDER','2024-09-01 10:00:00'),
(1010,'seed_Ishaan Reddy','seed_user10@test.com','Java,Kafka,Microservices','8 years in Enterprise',
 'Enterprise software veteran launching a startup.',
 'https://github.com/seed_ishaan','FOUNDER','2024-09-01 10:00:00'),
(1011,'seed_Shaurya Iyer','seed_user11@test.com','C++,Embedded Systems,IoT','5 years in Hardware',
 'Hardware startup building smart home devices.',
 'https://hackaday.io/seed_shaurya','FOUNDER','2024-09-01 10:00:00'),
(1012,'seed_Atharv Joshi','seed_user12@test.com','Django,PostgreSQL,Redis','4 years in ECommerce',
 'E-commerce founder scaling D2C brands.',
 'https://github.com/seed_atharv','FOUNDER','2024-09-01 10:00:00'),
(1013,'seed_Advik Rao','seed_user13@test.com','Scala,Spark,Hadoop','6 years in BigData',
 'Data engineering founder powering analytics at scale.',
 'https://linkedin.com/in/seed_advik','FOUNDER','2024-09-01 10:00:00'),
(1014,'seed_Dhruv Bhat','seed_user14@test.com','Solidity,Ethereum,Web3','3 years in Blockchain',
 'Building decentralized finance products on Ethereum.',
 'https://github.com/seed_dhruv','FOUNDER','2024-09-01 10:00:00'),
(1015,'seed_Kabir Das','seed_user15@test.com','Ruby on Rails,Heroku,AWS','5 years in SaaS',
 'SaaS founder with multiple exits.',
 'https://producthunt.com/seed_kabir','FOUNDER','2024-09-01 10:00:00'),
(1016,'seed_Ritvik Saxena','seed_user16@test.com','PHP,Laravel,MySQL','4 years in MarTech',
 'MarTech founder helping SMBs grow online.',
 'https://github.com/seed_ritvik','FOUNDER','2024-09-01 10:00:00'),
(1017,'seed_Aarush Patel','seed_user17@test.com','Next.js,Vercel,Supabase','3 years in PropTech',
 'PropTech founder digitizing real estate transactions.',
 'https://linkedin.com/in/seed_aarush','FOUNDER','2024-09-01 10:00:00'),
(1018,'seed_Darsh Mishra','seed_user18@test.com','Spring,Hibernate,Oracle','7 years in Banking',
 'Former banker building neobank for Gen-Z.',
 'https://github.com/seed_darsh','FOUNDER','2024-09-01 10:00:00'),
(1019,'seed_Pranav Tiwari','seed_user19@test.com','Elixir,Phoenix,GraphQL','4 years in HealthTech',
 'Health-tech founder improving patient outcomes.',
 'https://linkedin.com/in/seed_pranav','FOUNDER','2024-09-01 10:00:00'),
(1020,'seed_Arnav Pandey','seed_user20@test.com','Kotlin,Android,Jetpack Compose','3 years in InsurTech',
 'Simplifying insurance through mobile-first UX.',
 'https://github.com/seed_arnav','FOUNDER','2024-09-01 10:00:00'),
(1021,'seed_Yash Chaudhary','seed_user21@test.com','Vue.js,Nuxt,GraphQL','4 years in TravelTech',
 'Travel-tech founder building AI itinerary planner.',
 'https://linkedin.com/in/seed_yash','FOUNDER','2024-09-01 10:00:00'),
(1022,'seed_Rudra Malhotra','seed_user22@test.com','Java,Spring Cloud,RabbitMQ','5 years in LogisTech',
 'Logistics founder optimizing last-mile delivery.',
 'https://github.com/seed_rudra','FOUNDER','2024-09-01 10:00:00'),
(1023,'seed_Divyansh Kapoor','seed_user23@test.com','Python,Django,Celery','3 years in FoodTech',
 'Food-tech founder connecting home chefs with diners.',
 'https://producthunt.com/seed_divyansh','FOUNDER','2024-09-01 10:00:00'),
(1024,'seed_Parth Srivastava','seed_user24@test.com','React,Redux,Node.js','5 years in HRTech',
 'HR-tech founder building people-first software.',
 'https://github.com/seed_parth','FOUNDER','2024-09-01 10:00:00'),
(1025,'seed_Laksh Aggarwal','seed_user25@test.com','Machine Learning,NLP,BERT','6 years in AI',
 'NLP researcher turned conversational AI founder.',
 'https://huggingface.co/seed_laksh','FOUNDER','2024-09-01 10:00:00'),
(1026,'seed_Krish Ghosh','seed_user26@test.com','Terraform,AWS,GCP','5 years in CloudInfra',
 'Infrastructure founder enabling cloud-agnostic deployments.',
 'https://github.com/seed_krish','FOUNDER','2024-09-01 10:00:00'),
(1027,'seed_Harsh Chatterjee','seed_user27@test.com','Java,Microservices,Docker','4 years in RetailTech',
 'Retail-tech founder modernizing point-of-sale.',
 'https://linkedin.com/in/seed_harsh','FOUNDER','2024-09-01 10:00:00'),
(1028,'seed_Nikhil Banerjee','seed_user28@test.com','C#,.NET,Azure','6 years in GovTech',
 'GovTech founder digitizing public services.',
 'https://github.com/seed_nikhil','FOUNDER','2024-09-01 10:00:00'),
(1029,'seed_Rohan Mukherjee','seed_user29@test.com','Python,Flask,SQLAlchemy','4 years in CleanTech',
 'Clean-tech founder developing renewable energy marketplace.',
 'https://linkedin.com/in/seed_rohan','FOUNDER','2024-09-01 10:00:00'),
(1030,'seed_Uday Bose','seed_user30@test.com','Kotlin,Spring Boot,MongoDB','3 years in SportsTech',
 'Sports analytics founder empowering coaches with data.',
 'https://github.com/seed_uday','FOUNDER','2024-09-01 10:00:00'),
(1031,'seed_Samyak Sen','seed_user31@test.com','TypeScript,NestJS,Redis','4 years in EduTech',
 'EdTech founder creating adaptive learning experiences.',
 'https://github.com/seed_samyak','FOUNDER','2024-09-01 10:00:00'),
(1032,'seed_Devansh Roy','seed_user32@test.com','Go,gRPC,Kubernetes','5 years in CyberSec',
 'Cybersecurity founder building zero-trust solutions.',
 'https://github.com/seed_devansh','FOUNDER','2024-09-01 10:00:00'),
(1033,'seed_Vivek Dey','seed_user33@test.com','Angular,Spring MVC,MySQL','6 years in BFSI',
 'BFSI veteran launching micro-finance for tier-2 cities.',
 'https://linkedin.com/in/seed_vivek','FOUNDER','2024-09-01 10:00:00'),
(1034,'seed_Ayush Saha','seed_user34@test.com','React,AWS Lambda,DynamoDB','3 years in PetTech',
 'Pet health-tech founder disrupting veterinary space.',
 'https://github.com/seed_ayush','FOUNDER','2024-09-01 10:00:00'),
(1035,'seed_Karan Das','seed_user35@test.com','Python,FastAPI,Postgres','4 years in LegalTech',
 'Automating contract management for SMBs.',
 'https://github.com/seed_karan','FOUNDER','2024-09-01 10:00:00'),
(1036,'seed_Rishi Varma','seed_user36@test.com','Node,Express,MongoDB','3 years in SocialTech',
 'Social platform founder for professional communities.',
 'https://linkedin.com/in/seed_rishi','FOUNDER','2024-09-01 10:00:00'),
(1037,'seed_Ansh Nambiar','seed_user37@test.com','Rust,Tokio,WebSockets','5 years in FinTech',
 'High-frequency trading infrastructure founder.',
 'https://github.com/seed_ansh','FOUNDER','2024-09-01 10:00:00'),
(1038,'seed_Veer Menon','seed_user38@test.com','Swift,ARKit,CoreML','4 years in AR/VR',
 'AR founder building immersive retail experiences.',
 'https://github.com/seed_veer','FOUNDER','2024-09-01 10:00:00'),
(1039,'seed_Zayan Krishnan','seed_user39@test.com','Python,OpenCV,PyTorch','5 years in ComputerVision',
 'Computer vision founder for smart surveillance.',
 'https://github.com/seed_zayan','FOUNDER','2024-09-01 10:00:00'),
(1040,'seed_Dev Subramaniam','seed_user40@test.com','Java,Android,Firebase','3 years in EdTech',
 'Mobile-first education founder for rural India.',
 'https://github.com/seed_devs','FOUNDER','2024-09-01 10:00:00'),
(1041,'seed_Eshaan Pillai','seed_user41@test.com','Elixir,Phoenix,PostgreSQL','4 years in HRTech',
 'Real-time collaboration tools for distributed teams.',
 'https://github.com/seed_eshaan','FOUNDER','2024-09-01 10:00:00'),
(1042,'seed_Naman Hegde','seed_user42@test.com','React,TypeScript,GraphQL','5 years in Marketplace',
 'Two-sided marketplace founder for skilled gig workers.',
 'https://linkedin.com/in/seed_naman','FOUNDER','2024-09-01 10:00:00'),
(1043,'seed_Aayan Venkat','seed_user43@test.com','Python,Keras,TensorFlow','4 years in HealthAI',
 'AI diagnostics founder improving early cancer detection.',
 'https://github.com/seed_aayan','FOUNDER','2024-09-01 10:00:00'),
(1044,'seed_Sahil Prasad','seed_user44@test.com','Java,Spring Security,OAuth2','6 years in InfoSec',
 'Identity security founder protecting digital assets.',
 'https://github.com/seed_sahil','FOUNDER','2024-09-01 10:00:00'),
(1045,'seed_Tanish Kulkarni','seed_user45@test.com','Kotlin,Ktor,Room','3 years in ClimaTech',
 'Climate data platform founder for carbon tracking.',
 'https://linkedin.com/in/seed_tanish','FOUNDER','2024-09-01 10:00:00'),
(1046,'seed_Raghav Desai','seed_user46@test.com','Go,etcd,gRPC','5 years in CloudNative',
 'Distributed systems expert building cloud orchestration.',
 'https://github.com/seed_raghav','FOUNDER','2024-09-01 10:00:00'),
(1047,'seed_Ojas Wagh','seed_user47@test.com','Ruby,Sinatra,PostgreSQL','4 years in EventTech',
 'Event discovery platform connecting creators with audiences.',
 'https://github.com/seed_ojas','FOUNDER','2024-09-01 10:00:00'),
(1048,'seed_Siddharth Jain','seed_user48@test.com','Python,Django REST,Celery','5 years in AgriTech',
 'Precision agriculture founder leveraging IoT and ML.',
 'https://linkedin.com/in/seed_siddharth','FOUNDER','2024-09-01 10:00:00'),
(1049,'seed_Mihir Gadekar','seed_user49@test.com','Java,Hadoop,Hive','7 years in Analytics',
 'Data lakehouse founder democratizing business intelligence.',
 'https://github.com/seed_mihir','FOUNDER','2024-09-01 10:00:00'),
(1050,'seed_Aditya Naik','seed_user50@test.com','JavaScript,ThreeJS,WebGL','4 years in GameTech',
 '3D web game founder building browser-native experiences.',
 'https://github.com/seed_adityanaik','FOUNDER','2024-09-01 10:00:00'),
(1051,'seed_Parv Dalvi','seed_user51@test.com','Svelte,SvelteKit,PocketBase','3 years in ContentTech',
 'Content monetization founder for indie creators.',
 'https://github.com/seed_parv','FOUNDER','2024-09-01 10:00:00'),
(1052,'seed_Rachit More','seed_user52@test.com','Vue,Nuxt,Prisma','3 years in HospTech',
 'Hospitality tech founder digitizing hotel operations.',
 'https://linkedin.com/in/seed_rachit','FOUNDER','2024-09-01 10:00:00'),
(1053,'seed_Aryan Thakur','seed_user53@test.com','React,Redux Toolkit,RTK Query','4 years in RegTech',
 'RegTech founder automating compliance workflows.',
 'https://github.com/seed_aryan','FOUNDER','2024-09-01 10:00:00'),
(1054,'seed_Kunal Shinde','seed_user54@test.com','Deno,Oak,DenoKV','2 years in Web3',
 'Web3 infrastructure founder building decentralized CDN.',
 'https://github.com/seed_kunal','FOUNDER','2024-09-01 10:00:00'),
(1055,'seed_Omkar Patil','seed_user55@test.com','Haskell,Yesod,PostgreSQL','6 years in FinTech',
 'Formal verification enthusiast building secure fintech.',
 'https://github.com/seed_omkar','FOUNDER','2024-09-01 10:00:00'),
(1056,'seed_Viraj Pawar','seed_user56@test.com','Clojure,Datomic,Kafka','5 years in DataMesh',
 'Data mesh architect turned enterprise data startup founder.',
 'https://github.com/seed_viraj','FOUNDER','2024-09-01 10:00:00'),
(1057,'seed_Tejas Kadam','seed_user57@test.com','Erlang,RabbitMQ,Observer','7 years in Telecom',
 'Telecom startup founder improving network observability.',
 'https://github.com/seed_tejas','FOUNDER','2024-09-01 10:00:00'),
(1058,'seed_Yuvraj Bhosale','seed_user58@test.com','OCaml,Mirage,Irmin','5 years in Systems',
 'Systems programming founder building unikernel platform.',
 'https://github.com/seed_yuvraj','FOUNDER','2024-09-01 10:00:00'),
(1059,'seed_Advait Chavan','seed_user59@test.com','Nim,Prologue,PostgreSQL','3 years in DevTools',
 'Developer tooling founder improving CI/CD experience.',
 'https://github.com/seed_advait','FOUNDER','2024-09-01 10:00:00'),
(1060,'seed_Shreyash Gaikwad','seed_user60@test.com','Zig,LLVM,WebAssembly','4 years in Compilers',
 'Low-level systems founder building next-gen compiler toolchain.',
 'https://github.com/seed_shreyash','FOUNDER','2024-09-01 10:00:00'),
-- INVESTOR users (1061–1120)
(1061,'seed_Prem Agarwal','seed_user61@test.com','Angel Investing,Portfolio Mgmt,Due Diligence','15 years in VC',
 'Angel investor with 30+ portfolio companies.',
 'https://angel.co/u/seed_prem','INVESTOR','2024-09-01 10:00:00'),
(1062,'seed_Sonal Bajaj','seed_user62@test.com','Venture Capital,Market Research,Startup Mentoring','12 years in VC',
 'Partner at seed-stage VC focused on deep tech.',
 'https://linkedin.com/in/seed_sonal','INVESTOR','2024-09-01 10:00:00'),
(1063,'seed_Neha Birla','seed_user63@test.com','Private Equity,Growth Strategy,M&A','18 years in PE',
 'Growth equity investor backing series B startups.',
 'https://linkedin.com/in/seed_neha','INVESTOR','2024-09-01 10:00:00'),
(1064,'seed_Rahul Godrej','seed_user64@test.com','Startup Ecosystems,Go-to-market,B2B SaaS','10 years in VC',
 'B2B SaaS specialist helping founders scale globally.',
 'https://angel.co/u/seed_rahul','INVESTOR','2024-09-01 10:00:00'),
(1065,'seed_Sunita Tata','seed_user65@test.com','Impact Investing,ESG,ClimaTech','20 years in Impact',
 'Impact investor focused on climate-positive startups.',
 'https://linkedin.com/in/seed_sunita','INVESTOR','2024-09-01 10:00:00'),
(1066,'seed_Vijay Ambani','seed_user66@test.com','Family Office,Real Estate Tech,FinTech','25 years in Investments',
 'Family office principal diversifying into tech startups.',
 'https://linkedin.com/in/seed_vijay','INVESTOR','2024-09-01 10:00:00'),
(1067,'seed_Meena Jindal','seed_user67@test.com','Consumer Tech,Retail,D2C Brands','11 years in Consumer',
 'Consumer brand investor backing the next unicorns.',
 'https://angel.co/u/seed_meena','INVESTOR','2024-09-01 10:00:00'),
(1068,'seed_Ajay Mittal','seed_user68@test.com','Deep Tech,Space Tech,Defense','14 years in DeepTech',
 'Deep tech investor backing hard science startups.',
 'https://linkedin.com/in/seed_ajay','INVESTOR','2024-09-01 10:00:00'),
(1069,'seed_Priya Oberoi','seed_user69@test.com','HealthTech,BioTech,MedDevice','16 years in Health',
 'Healthcare investor bridging science and market.',
 'https://linkedin.com/in/seed_priya','INVESTOR','2024-09-01 10:00:00'),
(1070,'seed_Suresh Murthy','seed_user70@test.com','EdTech,Future of Work,HR Tech','13 years in EdTech invest',
 'Education and workforce transformation investor.',
 'https://angel.co/u/seed_suresh','INVESTOR','2024-09-01 10:00:00'),
(1071,'seed_Anita Rao','seed_user71@test.com','AgriTech,FoodTech,Rural Innovation','10 years in Agri invest',
 'AgroTech investor transforming food supply chains.',
 'https://linkedin.com/in/seed_anita','INVESTOR','2024-09-01 10:00:00'),
(1072,'seed_Rajesh Naidu','seed_user72@test.com','Mobility,EV Tech,Autonomous Vehicles','9 years in Mobility',
 'Mobility investor excited about the EV revolution.',
 'https://linkedin.com/in/seed_rajesh','INVESTOR','2024-09-01 10:00:00'),
(1073,'seed_Deepak Reddy','seed_user73@test.com','Crypto,DeFi,NFT Infrastructure','7 years in Web3 invest',
 'Web3 native investor finding alpha in decentralized finance.',
 'https://angel.co/u/seed_deepak','INVESTOR','2024-09-01 10:00:00'),
(1074,'seed_Kavita Menon','seed_user74@test.com','Media Tech,Content,Creator Economy','11 years in MediaTech',
 'Creator economy specialist investing in media infrastructure.',
 'https://linkedin.com/in/seed_kavita','INVESTOR','2024-09-01 10:00:00'),
(1075,'seed_Arun Nair','seed_user75@test.com','CyberSec,ZeroTrust,Cloud Security','12 years in Security invest',
 'Security-focused investor protecting digital enterprises.',
 'https://linkedin.com/in/seed_arun','INVESTOR','2024-09-01 10:00:00'),
(1076,'seed_Shalini Krishnan','seed_user76@test.com','GovTech,Smart Cities,Public Services','8 years in GovTech invest',
 'GovTech investor driving public sector digitization.',
 'https://angel.co/u/seed_shalini','INVESTOR','2024-09-01 10:00:00'),
(1077,'seed_Mohan Pillai','seed_user77@test.com','Retail Tech,Commerce,Payments','10 years in Retail invest',
 'RetailTech investor backing omnichannel innovators.',
 'https://linkedin.com/in/seed_mohan','INVESTOR','2024-09-01 10:00:00'),
(1078,'seed_Lakshmi Iyer','seed_user78@test.com','Women in Tech,Diversity Investing,SaaS','13 years in VC',
 'Diversity-focused investor championing underrepresented founders.',
 'https://linkedin.com/in/seed_lakshmi','INVESTOR','2024-09-01 10:00:00'),
(1079,'seed_Ganesh Bhat','seed_user79@test.com','Quantum Computing,Semiconductors,Hardware','15 years in DeepTech',
 'Quantum tech investor betting on next compute paradigm.',
 'https://linkedin.com/in/seed_ganesh','INVESTOR','2024-09-01 10:00:00'),
(1080,'seed_Suma Hegde','seed_user80@test.com','Robotics,Automation,Industrial IoT','12 years in Industrial',
 'Industrial automation investor powering Industry 4.0.',
 'https://angel.co/u/seed_suma','INVESTOR','2024-09-01 10:00:00'),
(1081,'seed_Ramesh Kamath','seed_user81@test.com','Logistics,Supply Chain,WMS','11 years in LogisTech invest',
 'Supply chain investor modernizing global trade.',
 'https://linkedin.com/in/seed_ramesh','INVESTOR','2024-09-01 10:00:00'),
(1082,'seed_Usha Shenoy','seed_user82@test.com','Energy Tech,SmartGrid,CleanEnergy','14 years in Energy invest',
 'Energy transition investor accelerating net-zero.',
 'https://linkedin.com/in/seed_usha','INVESTOR','2024-09-01 10:00:00'),
(1083,'seed_Vinod Pai','seed_user83@test.com','Ocean Tech,Blue Economy,Marine','9 years in OceanTech invest',
 'Blue economy investor backing sustainable ocean startups.',
 'https://angel.co/u/seed_vinod','INVESTOR','2024-09-01 10:00:00'),
(1084,'seed_Preethi Shetty','seed_user84@test.com','Mental Health,Wellness,Digital Therapeutics','8 years in HealthInvest',
 'Mental health investor building resilient communities.',
 'https://linkedin.com/in/seed_preethi','INVESTOR','2024-09-01 10:00:00'),
(1085,'seed_Harish Alva','seed_user85@test.com','Sports Analytics,Fitness Tech,Wearables','7 years in SportsTech invest',
 'Sports technology investor backing elite performance tools.',
 'https://linkedin.com/in/seed_harish','INVESTOR','2024-09-01 10:00:00'),
(1086,'seed_Jayanti Amin','seed_user86@test.com','Luxury Tech,Fashion Tech,Brands','11 years in Luxury invest',
 'Luxury brand technology investor.',
 'https://angel.co/u/seed_jayanti','INVESTOR','2024-09-01 10:00:00'),
(1087,'seed_Balaji Shah','seed_user87@test.com','LegalTech,Compliance,RegTech','10 years in LegalTech invest',
 'LegalTech investor automating access to justice.',
 'https://linkedin.com/in/seed_balaji','INVESTOR','2024-09-01 10:00:00'),
(1088,'seed_Chitra Joshi','seed_user88@test.com','Prop Tech,Construction Tech,Smart Buildings','12 years in PropInvest',
 'PropTech investor reshaping the built environment.',
 'https://linkedin.com/in/seed_chitra','INVESTOR','2024-09-01 10:00:00'),
(1089,'seed_Dinesh Kulkarni','seed_user89@test.com','InsurTech,Underwriting,Parametric Insurance','9 years in InsurInvest',
 'InsurTech investor building parametric risk products.',
 'https://angel.co/u/seed_dinesh','INVESTOR','2024-09-01 10:00:00'),
(1090,'seed_Eira Desai','seed_user90@test.com','AR VR,XR Enterprise,Spatial Computing','8 years in XR invest',
 'Spatial computing investor backing enterprise AR.',
 'https://linkedin.com/in/seed_eira','INVESTOR','2024-09-01 10:00:00'),
(1091,'seed_Farhan Merchant','seed_user91@test.com','Print on Demand,D2C,Ecom Infra','6 years in ecom invest',
 'E-commerce infrastructure investor.',
 'https://angel.co/u/seed_farhan','INVESTOR','2024-09-01 10:00:00'),
(1092,'seed_Geeta Wadia','seed_user92@test.com','Telehealth,Remote Diagnostics,MedAI','11 years in HealthInvest',
 'Telehealth specialist decentralizing patient care.',
 'https://linkedin.com/in/seed_geeta','INVESTOR','2024-09-01 10:00:00'),
(1093,'seed_Hitesh Doshi','seed_user93@test.com','Micro Mobility,EVs,Urban Transport','8 years in MobilityInvest',
 'Urban mobility investor electrifying last-mile transport.',
 'https://linkedin.com/in/seed_hitesh','INVESTOR','2024-09-01 10:00:00'),
(1094,'seed_Indira Kapasi','seed_user94@test.com','Women Entrepreneurs,Social Impact,Microfinance','16 years in Impact invest',
 'Social impact investor empowering women entrepreneurs.',
 'https://angel.co/u/seed_indira','INVESTOR','2024-09-01 10:00:00'),
(1095,'seed_Jiten Lathia','seed_user95@test.com','Pet Care,Vet Tech,Animal Health','5 years in PetInvest',
 'Pet health investor backed by love for animals.',
 'https://linkedin.com/in/seed_jiten','INVESTOR','2024-09-01 10:00:00'),
(1096,'seed_Kamal Mehta','seed_user96@test.com','Travel Tech,Hospitality,Experiences','9 years in TravelInvest',
 'TravelTech investor redefining hospitality post-pandemic.',
 'https://angel.co/u/seed_kamal','INVESTOR','2024-09-01 10:00:00'),
(1097,'seed_Leela Vora','seed_user97@test.com','Autonomous Drones,UAV,Delivery','8 years in DroneInvest',
 'Drone delivery investor enabling airspace commerce.',
 'https://linkedin.com/in/seed_leela','INVESTOR','2024-09-01 10:00:00'),
(1098,'seed_Mukesh Gada','seed_user98@test.com','Micro SaaS,Indie Hackers,Bootstrapped','7 years in MicroSaaS invest',
 'Micro-SaaS investor backing bootstrapped founders.',
 'https://angel.co/u/seed_mukesh','INVESTOR','2024-09-01 10:00:00'),
(1099,'seed_Nalini Trivedi','seed_user99@test.com','WaterTech,Sanitation,CleanWater','11 years in WaterInvest',
 'CleanWater investor ensuring safe water access.',
 'https://linkedin.com/in/seed_nalini','INVESTOR','2024-09-01 10:00:00'),
(1100,'seed_Omar Sheikh','seed_user100@test.com','NeuroTech,BCI,Neuroscience','10 years in NeuroInvest',
 'NeuroTech investor funding brain-computer interface research.',
 'https://angel.co/u/seed_omar','INVESTOR','2024-09-01 10:00:00'),
(1101,'seed_Padma Buch','seed_user101@test.com','Gaming,Esports,Metaverse','7 years in GameInvest',
 'Gaming and metaverse investor shaping virtual economies.',
 'https://linkedin.com/in/seed_padma','INVESTOR','2024-09-01 10:00:00'),
(1102,'seed_Qadir Hakim','seed_user102@test.com','NanoTech,Materials Science,Advanced Mfg','12 years in NanoInvest',
 'Materials science investor enabling next-gen manufacturing.',
 'https://angel.co/u/seed_qadir','INVESTOR','2024-09-01 10:00:00'),
(1103,'seed_Renu Dalal','seed_user103@test.com','Biodiversity,ConservaTech,EcoSystem','9 years in EcoInvest',
 'Conservation tech investor protecting natural ecosystems.',
 'https://linkedin.com/in/seed_renu','INVESTOR','2024-09-01 10:00:00'),
(1104,'seed_Santosh Ghosh','seed_user104@test.com','Robotics,Automation,Factory OS','11 years in RoboInvest',
 'Robotics investor automating the shop floor.',
 'https://angel.co/u/seed_santosh','INVESTOR','2024-09-01 10:00:00'),
(1105,'seed_Taruna Bansal','seed_user105@test.com','Social Commerce,Community,Live Shopping','6 years in SocialInvest',
 'Social commerce investor powering community-led growth.',
 'https://linkedin.com/in/seed_taruna','INVESTOR','2024-09-01 10:00:00'),
(1106,'seed_Uma Chauhan','seed_user106@test.com','Renewable Energy,SolarTech,GridStorage','14 years in RenewInvest',
 'Renewable energy investor accelerating solar adoption.',
 'https://linkedin.com/in/seed_uma','INVESTOR','2024-09-01 10:00:00'),
(1107,'seed_Varsha Saxena','seed_user107@test.com','Digital Health,Remote Patient Monitoring,Devices','10 years in DigiHealth invest',
 'Digital health investor improving chronic care management.',
 'https://angel.co/u/seed_varsha','INVESTOR','2024-09-01 10:00:00'),
(1108,'seed_Waman Kelkar','seed_user108@test.com','Smart Manufacturing,Quality Control,Vision AI','9 years in MfgInvest',
 'Manufacturing intelligence investor deploying computer vision.',
 'https://linkedin.com/in/seed_waman','INVESTOR','2024-09-01 10:00:00'),
(1109,'seed_Xena Puri','seed_user109@test.com','Language Learning,EdTech,AI Tutors','8 years in LangInvest',
 'Language education investor scaling multilingual AI tutors.',
 'https://angel.co/u/seed_xena','INVESTOR','2024-09-01 10:00:00'),
(1110,'seed_Yogesh Batra','seed_user110@test.com','FinTech Infrastructure,Payments API,Open Banking','13 years in FinInfraInvest',
 'FinTech infrastructure investor enabling embedded finance.',
 'https://linkedin.com/in/seed_yogesh','INVESTOR','2024-09-01 10:00:00'),
(1111,'seed_Zara Khanna','seed_user111@test.com','SME Finance,MSME Lending,Invoice Discounting','10 years in MSMEInvest',
 'MSME finance investor unlocking capital for small businesses.',
 'https://angel.co/u/seed_zara','INVESTOR','2024-09-01 10:00:00'),
(1112,'seed_Alok Sood','seed_user112@test.com','Carbon Credits,Climate Finance,ESG Risk','11 years in ClimateFinInvest',
 'Carbon market investor structuring climate finance deals.',
 'https://linkedin.com/in/seed_alok','INVESTOR','2024-09-01 10:00:00'),
(1113,'seed_Brij Khurana','seed_user113@test.com','Waste Management,CircularEconomy,Upcycling','8 years in CircEconInvest',
 'Circular economy investor closing the loop on waste.',
 'https://angel.co/u/seed_brij','INVESTOR','2024-09-01 10:00:00'),
(1114,'seed_Chanda Lal','seed_user114@test.com','Smart Textiles,Wearable Computing,FashionTech','7 years in WearInvest',
 'Smart textiles investor weaving tech into fabric.',
 'https://linkedin.com/in/seed_chanda','INVESTOR','2024-09-01 10:00:00'),
(1115,'seed_Devdas Madan','seed_user115@test.com','Bioprinting,Tissue Engineering,Synthetic Bio','12 years in BioInvest',
 'Biotech investor funding synthetic biology breakthroughs.',
 'https://angel.co/u/seed_devdas','INVESTOR','2024-09-01 10:00:00'),
(1116,'seed_Ekta Nagpal','seed_user116@test.com','Genomics,Personalized Medicine,Diagnostics','11 years in GenomicsInvest',
 'Genomics investor enabling precision medicine at scale.',
 'https://linkedin.com/in/seed_ekta','INVESTOR','2024-09-01 10:00:00'),
(1117,'seed_Falguni Seth','seed_user117@test.com','Alternative Proteins,FutureFoods,AgBioTech','9 years in FoodBioInvest',
 'Alternative protein investor building sustainable food systems.',
 'https://angel.co/u/seed_falguni','INVESTOR','2024-09-01 10:00:00'),
(1118,'seed_Gopal Wadhwa','seed_user118@test.com','Fleet Management,Telematics,Connected Vehicles','10 years in FleetInvest',
 'Fleet tech investor connecting commercial vehicles.',
 'https://linkedin.com/in/seed_gopal','INVESTOR','2024-09-01 10:00:00'),
(1119,'seed_Hema Jhunjhunwala','seed_user119@test.com','Blockchain Infrastructure,Layer2,ZKProofs','8 years in BlockchainInvest',
 'Blockchain investor scaling layer-2 protocol adoption.',
 'https://angel.co/u/seed_hema','INVESTOR','2024-09-01 10:00:00'),
(1120,'seed_Ilesh Parekh','seed_user120@test.com','Procurement Tech,B2B Marketplace,Trade Finance','12 years in ProcInvest',
 'Procurement technology investor digitizing B2B commerce.',
 'https://linkedin.com/in/seed_ilesh','INVESTOR','2024-09-01 10:00:00'),
-- COFOUNDER users (1121–1180)
(1121,'seed_Jignesh Mody','seed_user121@test.com','React,Node.js,iOS','4 years in Mobile Development',
 'Full-stack cofounder with mobile expertise.',
 'https://github.com/seed_jignesh','COFOUNDER','2024-09-01 10:00:00'),
(1122,'seed_Kirti Sheth','seed_user122@test.com','UX Design,Figma,User Research','5 years in Product Design',
 'Product designer turned cofounder focused on user delight.',
 'https://dribbble.com/seed_kirti','COFOUNDER','2024-09-01 10:00:00'),
(1123,'seed_Laleh Irani','seed_user123@test.com','Sales,CRM,Business Development','6 years in Enterprise Sales',
 'Sales-first cofounder closing enterprise deals.',
 'https://linkedin.com/in/seed_laleh','COFOUNDER','2024-09-01 10:00:00'),
(1124,'seed_Mahesh Dani','seed_user124@test.com','DevOps,CI/CD,Cloud Architecture','7 years in Infrastructure',
 'Infrastructure cofounder keeping systems rock solid.',
 'https://github.com/seed_mahesh','COFOUNDER','2024-09-01 10:00:00'),
(1125,'seed_Nalesh Soni','seed_user125@test.com','Marketing,SEO,Content Strategy','5 years in Digital Marketing',
 'Growth marketing cofounder scaling B2C products.',
 'https://linkedin.com/in/seed_nalesh','COFOUNDER','2024-09-01 10:00:00'),
(1126,'seed_Omesh Bolia','seed_user126@test.com','Finance,FP&A,Fundraising','8 years in CFO Track',
 'Finance cofounder optimizing runway and unit economics.',
 'https://linkedin.com/in/seed_omesh','COFOUNDER','2024-09-01 10:00:00'),
(1127,'seed_Paresh Koradia','seed_user127@test.com','Backend,Java,Distributed Systems','6 years in Backend',
 'Backend systems cofounder scaling APIs to millions.',
 'https://github.com/seed_paresh','COFOUNDER','2024-09-01 10:00:00'),
(1128,'seed_Quresh Habib','seed_user128@test.com','ML Engineering,MLOps,Feature Stores','5 years in MLOps',
 'ML engineering cofounder bridging research and production.',
 'https://github.com/seed_quresh','COFOUNDER','2024-09-01 10:00:00'),
(1129,'seed_Rajni Bhatt','seed_user129@test.com','Operations,Supply Chain,Vendor Mgmt','9 years in Operations',
 'Operations cofounder bringing startup execution excellence.',
 'https://linkedin.com/in/seed_rajni','COFOUNDER','2024-09-01 10:00:00'),
(1130,'seed_Sarla Trivedi','seed_user130@test.com','Legal,Compliance,IP Strategy','10 years in Law',
 'Legal cofounder protecting startup IP and contracts.',
 'https://linkedin.com/in/seed_sarla','COFOUNDER','2024-09-01 10:00:00'),
(1131,'seed_Tushar Garg','seed_user131@test.com','Data Science,BI,Dashboards','5 years in Analytics',
 'Data science cofounder turning data into decisions.',
 'https://github.com/seed_tushar','COFOUNDER','2024-09-01 10:00:00'),
(1132,'seed_Urvashi Baxi','seed_user132@test.com','HR,Talent Acquisition,Culture Building','7 years in HR',
 'People-first cofounder building exceptional company culture.',
 'https://linkedin.com/in/seed_urvashi','COFOUNDER','2024-09-01 10:00:00'),
(1133,'seed_Vatsal Majmudar','seed_user133@test.com','Security,Penetration Testing,AppSec','6 years in CyberSec',
 'Security cofounder ensuring compliance from day one.',
 'https://github.com/seed_vatsal','COFOUNDER','2024-09-01 10:00:00'),
(1134,'seed_Wina Pandya','seed_user134@test.com','Community,Growth Hacking,Partnerships','4 years in Community Building',
 'Community-first cofounder growing viral loops.',
 'https://linkedin.com/in/seed_wina','COFOUNDER','2024-09-01 10:00:00'),
(1135,'seed_Xavier Pinto','seed_user135@test.com','Hardware Engineering,PCB Design,Firmware','8 years in Hardware',
 'Hardware cofounder prototyping physical products.',
 'https://github.com/seed_xavier','COFOUNDER','2024-09-01 10:00:00'),
(1136,'seed_Yolanda Madeira','seed_user136@test.com','Data Engineering,ETL,dbt,Airflow','5 years in Data Eng',
 'Data engineering cofounder powering analytics pipelines.',
 'https://github.com/seed_yolanda','COFOUNDER','2024-09-01 10:00:00'),
(1137,'seed_Zaheer Ansari','seed_user137@test.com','Customer Success,Churn Reduction,NPS','6 years in Customer Success',
 'Customer success cofounder maximizing lifetime value.',
 'https://linkedin.com/in/seed_zaheer','COFOUNDER','2024-09-01 10:00:00'),
(1138,'seed_Asha Rastogi','seed_user138@test.com','Product Management,Roadmaps,OKRs','7 years in Product',
 'PM cofounder translating vision into shipping velocity.',
 'https://linkedin.com/in/seed_asha','COFOUNDER','2024-09-01 10:00:00'),
(1139,'seed_Bhanu Kapila','seed_user139@test.com','Blockchain,Smart Contracts,Tokenomics','5 years in Web3',
 'Web3 cofounder designing sustainable token economies.',
 'https://github.com/seed_bhanu','COFOUNDER','2024-09-01 10:00:00'),
(1140,'seed_Chetan Kohli','seed_user140@test.com','SEO,Performance Marketing,Analytics','6 years in Digital',
 'Performance marketing cofounder acquiring users profitably.',
 'https://linkedin.com/in/seed_chetan','COFOUNDER','2024-09-01 10:00:00'),
(1141,'seed_Diya Bose','seed_user141@test.com','Video Production,Motion Design,Brand','4 years in Creative',
 'Creative cofounder building memorable brand identities.',
 'https://behance.net/seed_diya','COFOUNDER','2024-09-01 10:00:00'),
(1142,'seed_Esha Saha','seed_user142@test.com','QA,Test Automation,Selenium,Playwright','6 years in QA',
 'QA cofounder ensuring product reliability at speed.',
 'https://github.com/seed_esha','COFOUNDER','2024-09-01 10:00:00'),
(1143,'seed_Farida Haider','seed_user143@test.com','Research,PhD Chemistry,Lab Automation','8 years in Research',
 'Science cofounder bridging lab research and commercial product.',
 'https://scholar.google.com/seed_farida','COFOUNDER','2024-09-01 10:00:00'),
(1144,'seed_Girija Nambiar','seed_user144@test.com','International Expansion,APAC,Localization','9 years in BD',
 'International BD cofounder opening APAC markets.',
 'https://linkedin.com/in/seed_girija','COFOUNDER','2024-09-01 10:00:00'),
(1145,'seed_Harsha Varrier','seed_user145@test.com','Mechanical Engineering,CAD,Prototyping','7 years in Mechanical Eng',
 'Mechanical engineering cofounder industrializing prototypes.',
 'https://github.com/seed_harsha','COFOUNDER','2024-09-01 10:00:00'),
(1146,'seed_Ila Goswami','seed_user146@test.com','Regulatory Affairs,FDA,CE Marking','10 years in RegAffairs',
 'Regulatory cofounder navigating compliance for medtech.',
 'https://linkedin.com/in/seed_ila','COFOUNDER','2024-09-01 10:00:00'),
(1147,'seed_Jagdish Thakkar','seed_user147@test.com','Accounting,Financial Modeling,Fundraising','8 years in Finance',
 'CFO-track cofounder structuring term sheets.',
 'https://linkedin.com/in/seed_jagdish','COFOUNDER','2024-09-01 10:00:00'),
(1148,'seed_Kamla Bhardwaj','seed_user148@test.com','Industrial Design,3D Printing,Materials','6 years in Ind Design',
 'Industrial design cofounder iterating on product form.',
 'https://behance.net/seed_kamla','COFOUNDER','2024-09-01 10:00:00'),
(1149,'seed_Lata Shukla','seed_user149@test.com','Healthcare Operations,Clinical Trials,Protocol Design','11 years in ClinicOps',
 'Clinical operations cofounder running safe trials.',
 'https://linkedin.com/in/seed_lata','COFOUNDER','2024-09-01 10:00:00'),
(1150,'seed_Madhu Verma','seed_user150@test.com','Social Media,Influencer Marketing,Viral Content','5 years in Social',
 'Social media cofounder building creator-led growth.',
 'https://linkedin.com/in/seed_madhu','COFOUNDER','2024-09-01 10:00:00'),
(1151,'seed_Nandini Yadav','seed_user151@test.com','Event Management,Partnerships,Sponsorships','6 years in Events',
 'Events cofounder orchestrating launch moments.',
 'https://linkedin.com/in/seed_nandini','COFOUNDER','2024-09-01 10:00:00'),
(1152,'seed_Omi Jain','seed_user152@test.com','Supply Chain Finance,Factoring,Working Capital','9 years in TradeFinance',
 'Trade finance cofounder unlocking supply chain capital.',
 'https://linkedin.com/in/seed_omi','COFOUNDER','2024-09-01 10:00:00'),
(1153,'seed_Pankaj Tomar','seed_user153@test.com','DevRel,Technical Writing,API Docs','5 years in DevRel',
 'Developer relations cofounder winning hearts of engineers.',
 'https://github.com/seed_pankaj','COFOUNDER','2024-09-01 10:00:00'),
(1154,'seed_Radha Swami','seed_user154@test.com','Aerospace Engineering,Propulsion,Systems','10 years in Aerospace',
 'Aerospace cofounder building sub-orbital launch vehicles.',
 'https://github.com/seed_radha','COFOUNDER','2024-09-01 10:00:00'),
(1155,'seed_Sanjeev Rawat','seed_user155@test.com','Embedded Linux,RTOS,BSP Development','8 years in Embedded',
 'Embedded systems cofounder shipping reliable firmware.',
 'https://github.com/seed_sanjeev','COFOUNDER','2024-09-01 10:00:00'),
(1156,'seed_Tanuja Bisht','seed_user156@test.com','PR,Media Relations,Crisis Communications','7 years in PR',
 'Communications cofounder shaping startup narratives.',
 'https://linkedin.com/in/seed_tanuja','COFOUNDER','2024-09-01 10:00:00'),
(1157,'seed_Uday Nautiyal','seed_user157@test.com','Environmental Science,Life Cycle Analysis,ESG Reporting','9 years in Sustainability',
 'Sustainability cofounder measuring environmental impact.',
 'https://linkedin.com/in/seed_uday','COFOUNDER','2024-09-01 10:00:00'),
(1158,'seed_Varun Dimri','seed_user158@test.com','Animation,3D Modeling,Blender','5 years in CGI',
 'CGI cofounder crafting immersive visual experiences.',
 'https://behance.net/seed_varun','COFOUNDER','2024-09-01 10:00:00'),
(1159,'seed_Winnie Bora','seed_user159@test.com','Linguistics,Language Models,NLU','7 years in NLP',
 'NLP research cofounder building multilingual AI.',
 'https://github.com/seed_winnie','COFOUNDER','2024-09-01 10:00:00'),
(1160,'seed_Xenia Lama','seed_user160@test.com','Mountain Guides,Outdoor Tech,TrailApps','4 years in OutdoorTech',
 'Outdoor tech cofounder connecting adventure communities.',
 'https://linkedin.com/in/seed_xenia','COFOUNDER','2024-09-01 10:00:00'),
(1161,'seed_Yana Ghimirey','seed_user161@test.com','Nanotechnology,Drug Delivery,Biocompatibility','10 years in Nanotech',
 'Nanotech cofounder enabling targeted drug delivery.',
 'https://scholar.google.com/seed_yana','COFOUNDER','2024-09-01 10:00:00'),
(1162,'seed_Zubin Damania','seed_user162@test.com','Healthcare Reform,Physician Led,DPC','12 years in Medicine',
 'Physician cofounder reforming primary care models.',
 'https://linkedin.com/in/seed_zubin','COFOUNDER','2024-09-01 10:00:00'),
(1163,'seed_Anika Sood','seed_user163@test.com','Cognitive Science,HCI,Brain-Computer Interface','6 years in HCI',
 'HCI cofounder designing the next human-computer interface.',
 'https://github.com/seed_anika','COFOUNDER','2024-09-01 10:00:00'),
(1164,'seed_Bimal Dutt','seed_user164@test.com','Supply Chain,ERP,D365','8 years in ERP',
 'ERP specialist cofounder modernizing enterprise supply chains.',
 'https://linkedin.com/in/seed_bimal','COFOUNDER','2024-09-01 10:00:00'),
(1165,'seed_Charu Bhandari','seed_user165@test.com','Genomic Sequencing,CRISPR,Gene Editing','11 years in Gene Tech',
 'Gene editing cofounder advancing agricultural biotechnology.',
 'https://scholar.google.com/seed_charu','COFOUNDER','2024-09-01 10:00:00'),
(1166,'seed_Dhanesh Upreti','seed_user166@test.com','Predictive Maintenance,DigitalTwin,Industry4','7 years in Industry4',
 'Industry 4.0 cofounder reducing unplanned downtime.',
 'https://github.com/seed_dhanesh','COFOUNDER','2024-09-01 10:00:00'),
(1167,'seed_Ela Panthi','seed_user167@test.com','Venture Debt,Structured Finance,SPVs','9 years in VentDebt',
 'Structured finance cofounder innovating venture debt.',
 'https://linkedin.com/in/seed_ela','COFOUNDER','2024-09-01 10:00:00'),
(1168,'seed_Fiza Qureshi','seed_user168@test.com','Fashion Design,Sustainable Fashion,Circular','5 years in FashTech',
 'Fashion tech cofounder building circular clothing marketplace.',
 'https://behance.net/seed_fiza','COFOUNDER','2024-09-01 10:00:00'),
(1169,'seed_Gyan Silwal','seed_user169@test.com','Mountain Computing,Edge AI,Low-Power','6 years in EdgeAI',
 'Edge AI cofounder deploying intelligence at the network edge.',
 'https://github.com/seed_gyan','COFOUNDER','2024-09-01 10:00:00'),
(1170,'seed_Hira Malla','seed_user170@test.com','Social Entrepreneurship,Impact Measurement,B-Corp','8 years in Impact',
 'Impact measurement cofounder quantifying social ROI.',
 'https://linkedin.com/in/seed_hira','COFOUNDER','2024-09-01 10:00:00'),
(1171,'seed_Ishan Maskey','seed_user171@test.com','Earthquake Engineering,Disaster Tech,Resilience','9 years in DisasterTech',
 'Disaster resilience cofounder building early warning systems.',
 'https://github.com/seed_ishan','COFOUNDER','2024-09-01 10:00:00'),
(1172,'seed_Jaya Shrestha','seed_user172@test.com','Micro Finance,BNPL,Credit Scoring','7 years in MicroFinance',
 'Micro-credit cofounder bringing BNPL to underserved markets.',
 'https://linkedin.com/in/seed_jaya','COFOUNDER','2024-09-01 10:00:00'),
(1173,'seed_Kiran Basnet','seed_user173@test.com','Hydropower,Energy Storage,Smart Grid','10 years in Energy',
 'Hydropower cofounder balancing grid with clean energy.',
 'https://linkedin.com/in/seed_kiran','COFOUNDER','2024-09-01 10:00:00'),
(1174,'seed_Lima Rai','seed_user174@test.com','Culture,Anthropology,Community Research','5 years in Cultural',
 'Culture research cofounder localizing global products.',
 'https://linkedin.com/in/seed_lima','COFOUNDER','2024-09-01 10:00:00'),
(1175,'seed_Mina Tamang','seed_user175@test.com','Cartography,GeoSpatial,QGIS','6 years in GeoData',
 'Geospatial cofounder mapping the physical world for digital apps.',
 'https://github.com/seed_mina','COFOUNDER','2024-09-01 10:00:00'),
(1176,'seed_Nita Karki','seed_user176@test.com','Journalism,Media,Fact Checking','8 years in Media',
 'Media integrity cofounder building trust in digital news.',
 'https://linkedin.com/in/seed_nita','COFOUNDER','2024-09-01 10:00:00'),
(1177,'seed_Ojha Poudel','seed_user177@test.com','Sports Coaching,Performance Analytics,Biomechanics','7 years in SportsSci',
 'Sports science cofounder training elite athletes with data.',
 'https://linkedin.com/in/seed_ojha','COFOUNDER','2024-09-01 10:00:00'),
(1178,'seed_Pita Gurung','seed_user178@test.com','Tea Cultivation,AgriExport,Quality Certification','9 years in AgriExport',
 'Agri-export cofounder connecting farmers to global markets.',
 'https://linkedin.com/in/seed_pita','COFOUNDER','2024-09-01 10:00:00'),
(1179,'seed_Rina Magar','seed_user179@test.com','Textbook Publishing,Open Education,MOOC','6 years in EdPublish',
 'Open education cofounder reducing cost of learning.',
 'https://github.com/seed_rina','COFOUNDER','2024-09-01 10:00:00'),
(1180,'seed_Sita Thapa','seed_user180@test.com','Handcraft,Artisan,Fair Trade','5 years in FairTrade',
 'Fair trade cofounder empowering artisans with digital platforms.',
 'https://linkedin.com/in/seed_sita','COFOUNDER','2024-09-01 10:00:00');

SET foreign_key_checks = 1;
-- END user-service/seed.sql
-- Total rows: 200
